bindPort = 7000
auth.token = "d0597eaf862b2fb1b5ea570492aba736"

# 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
webServer.addr = "0.0.0.0"
webServer.port = 7500
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "fengming1201"

#webServer.tls.certFile = "server.crt"
#webServer.tls.keyFile = "server.key"